    name: HealthControl
    main: me.JamieSinn.Bukkit.HealthControl
    version: 1.0
    description: >
                 HealthControl Plugin.
    commands:
      heal:
        description: Heals a/the player.
      seehealth:
        description: Allows you to see a/the players health.
